// Thin Swift façade over the C ABI in bridge/include/mozc_bridge.h.
//
// The C symbols (mozc_bridge_init, mozc_bridge_convert, …) are imported via
// the bridging header generated by the Makefile. We hide the raw pointer
// dance here so main.swift only sees idiomatic Swift.
//
// Stage 1: the underlying implementation is a placeholder ("[bridge] ...").
// Stage 2: same Swift API; underneath it'll be a real MozcDirectClient call.

import Foundation

enum MozcBridgeError: Error {
    case notInitialized
    case conversionFailed(String)
    case stringEncoding
}

enum MozcBridge {
    /// Initialize the engine. Call once at startup. Subsequent calls are no-ops.
    /// `userProfileDir` is an optional path mozc will use for its on-disk state
    /// (user dictionary, history, config). nil → engine default.
    static func initialize(userProfileDir: String? = nil) throws {
        let cstr = userProfileDir.flatMap { $0.cString(using: .utf8) }
        let rc = cstr.withUnsafeBufferPointerOrNil { ptr in
            mozc_bridge_init(ptr)
        }
        if rc != 0 {
            throw MozcBridgeError.conversionFailed(lastError() ?? "init failed (rc=\(rc))")
        }
    }

    /// Target shape for a conversion call. `.kanji` is the default (Mozc's
    /// top kanji candidate); `.katakana` forces full-width katakana, useful
    /// for loanwords Mozc keeps trying to write as kanji.
    enum ConvertTarget {
        case kanji
        case katakana

        var bridgeFlags: UInt32 {
            switch self {
            case .kanji:    return 0
            case .katakana: return UInt32(MOZC_CONVERT_FLAG_KATAKANA)
            }
        }
    }

    /// Convert a UTF-8 romaji string into its top-candidate Japanese form.
    /// Returns the converted string; throws on engine error.
    static func convert(_ romaji: String, target: ConvertTarget = .kanji) throws -> String {
        guard let utf8 = romaji.cString(using: .utf8) else {
            throw MozcBridgeError.stringEncoding
        }
        // Drop the trailing NUL we don't want to send across the boundary.
        let utf8Bytes = utf8.dropLast()
        let inputLen = utf8Bytes.count
        let flags = target.bridgeFlags

        // Start with a reasonable buffer; grow once if needed.
        var cap = max(inputLen * 4 + 64, 256)
        while true {
            var outLen: Int = 0
            var buf = [CChar](repeating: 0, count: cap)
            let rc = utf8.withUnsafeBufferPointer { inPtr -> Int32 in
                buf.withUnsafeMutableBufferPointer { outPtr -> Int32 in
                    return Int32(mozc_bridge_convert_ex(
                        inPtr.baseAddress,
                        inputLen,
                        outPtr.baseAddress,
                        cap,
                        &outLen,
                        flags
                    ))
                }
            }
            if rc == 0 {
                let data = Data(bytes: buf, count: outLen)
                guard let s = String(data: data, encoding: .utf8) else {
                    throw MozcBridgeError.stringEncoding
                }
                return s
            }
            if rc < 0 {
                throw MozcBridgeError.conversionFailed(lastError() ?? "convert rc=\(rc)")
            }
            // Buffer too small: rc is the required size.
            cap = Int(rc) + 1
            if cap > 1 << 20 {  // sanity cap at 1 MiB
                throw MozcBridgeError.conversionFailed("convert wants \(cap) bytes (unreasonably large)")
            }
        }
    }

    /// Last error string set by the C layer on this thread, or nil.
    static func lastError() -> String? {
        guard let cstr = mozc_bridge_last_error() else { return nil }
        return String(cString: cstr)
    }
}

// Helper: pass-through nil if the optional is nil, otherwise expose buffer.
fileprivate extension Optional where Wrapped == [CChar] {
    func withUnsafeBufferPointerOrNil<R>(_ body: (UnsafePointer<CChar>?) -> R) -> R {
        if let arr = self {
            return arr.withUnsafeBufferPointer { body($0.baseAddress) }
        }
        return body(nil)
    }
}
